config/routes.rb
Rails.application.routes.draw do

  resources :places
  resources :reviews

  devise_for :users, controllers: { registrations: "registrations"}

  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

end

app/models/place.rb
class Place < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :phone
	validates_presence_of :address
	validates_presence_of :website
	validates_presence_of :user_id
	belongs_to :user

	geocoded_by :address
	after_validation :geocode

	has_many :reviews, dependent: :destroy

	def average_rating
		self.reviews.sum(:score) / reviews.size
	rescue ZeroDivisionError
		0
	end

	def self.search(search)
		if search
			where(['name LIKE ? OR address LIKE ?', "#{search}", "#{search}"])
		else
			all
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :place

	validates_presence_of :score
	validates_presence_of :content

	after_save :calculate_average

	def calculate_average
		a = self.place.average_rating
		self.place.update_attributes(total_average_rating: a)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  has_many :places, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]

  def home
  	if current_user
  		redirect_to dashboard_path
  	end
  end

  def dashboard
  	@user = current_user
  	@places = @user.places
  	@reviews = @user.reviews
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.search(params[:search])
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @reviews = @place.reviews
    if current_user
      @review = Review.new
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = current_user.places.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :description, :phone, :website)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_review, only: [:edit, :update, :destroy]

	def edit
		@place = @review.place
	end

	def create
		@review = current_user.reviews.new(review_params)

		respond_to do |format|
			if @review.save
				format.html { redirect_to place_path(@review.place), notice: 'Review was successfully created.' }
			else
				format.html { redirect_to place_path(@review.place), notice: "Something went wrong" }
			end
		end
	end

	def update
		respond_to do |format|
			if @review.update(review_params)
				format.html { redirect_to place_path(@review.place), notice: 'Review was successfully updated.' }
			else
				format.html { redirect_to place_path(@review.place), notice: "Something went wrong" }
			end
		end
	end

	def destroy
		@review.destroy
		respond_to do |format|
			format.html { redirect_to place_path(@review.place), notice: 'Review was successfully destroyed.' }
		end
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def review_params
		params.require(:review).permit(:content, :place_id, :score)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stukplaces", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><%= link_to "Places", places_path %></li>
        
      </ul>


      <%= form_tag places_path, method: "get", class: "navbar-form navbar-left" do %>

        <div class="form-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Type a place" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-default" %>

      <% end %>


      <ul class="nav navbar-nav navbar-right">
        
        <% if current_user %>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
        <% end %>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukplaces</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDd60iJ3DJ0iK8h_mOpFJKtohl4sqfncQY">
    </script>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |type, message| %>
<div class="alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>
<%= message %>
</div>
<% end %>
<% if current_page?(root_path) %>
<div class="landing">
<% else %>
<div class="container">
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">

<!-- Profile info -->
	<div class="col-md-2">
	<h3><%= @user.name %></h3>
	<%= gravatar_tag @user.email, size: 150 %>
	</div>

<!-- Places -->
	<div class="col-md-5">
	<h3>My Places</h3>

	<table class="table">

	<thead>
		<tr>
		<th>Name</th>
		<th>Created</th>
		<th></th>
		</tr>
	</thead>

	<tbody>

	<% @places.each do |place| %>

		<tr>
			<td><%= link_to place.name, place_path(place) %></td>
			<td><%= time_ago_in_words(place.created_at) %> ago</td>
			<td><%= link_to "Edit", edit_place_path(place) %> | <%= link_to "Destroy", place_path(place), method: :delete %></td>
		</tr>

	<% end %>

	</tbody>

	</table>
	<%= link_to "New Place", new_place_path %>

	</div>

<!-- Reviews -->
	<div class="col-md-5">
		<h3>My Reviews</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Place</th>
					<th>Created</th>
					<th>Rating</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @reviews.each do |review| %>
					<tr>
						<td><%= link_to review.place.name, place_path(review.place) %></td>
						<td><%= time_ago_in_words(review.created_at) %> ago</td>
						<td><div class="score_<%= review.id %>"></div></td>
						<td><%= link_to "Edit", edit_review_path(review) %> | <%= link_to "Destroy", review_path(review), method: :delete %></td>
					</tr>

				<% end %>
			</tbody>
		</table>
	</div>

</div>

<script type="text/javascript">
	 <% @reviews.each do |review| %>
      $(".score_<%= review.id %>").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= review.score %>,
        readOnly: true
      });
      <% end %>
</script>

app/views/pages/home.html.erb
<div class="text-center landing_title">
	<%= link_to "Find places you'll fall in love with", places_path, class: "btn btn-default btn-lg btn-landing" %>
</div>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :address, required: true %>
    <%= f.input :description %>
    <%= f.input :phone, required: true %>
    <%= f.input :website, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing Places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Average</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place_path(place) %></td>
        <td><%= place.address %></td>
        <td><%= place.phone %></td>
        <td><%= place.website %></td>
        <td><div class="average_<%= place.id %>"></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New Place', new_place_path %>
<% end %>

<script type="text/javascript">
  
  <% @places.each do |place| %>
      $(".average_<%= place.id %>").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= place.total_average_rating %>,
        readOnly: true
      });
      <% end %>

</script>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="row">
<div class="col-md-3">
<h3><%= @place.name %></h3>
<div class="average"></div>
<p>
<strong>Address</strong>
<%= @place.address %>
</p>
<p>
<strong>Phone</strong>
<%= @place.phone %>
</p>
<p>
<strong>Website</strong>
<%= @place.website %>
</p>
<p>
<strong>Description</strong>
<%= @place.description %>
</p>
<div id="map-canvas" style="width: 230px; height: 230px;"></div>

</div>

<div class="col-md-9">
<h3>Reviews by People</h3>
<% if current_user %>
<h5>New Review</h5>
<%= render "reviews/form" %>
<% end %>
<h5>All Reviews</h5>
<%= render @reviews %>

</div>

</div>



<script type="text/javascript">
      function initialize() {
        var mycenter = { lat: <%= @place.latitude %>, lng: <%= @place.longitude %>}
        var mapOptions = {
          center: mycenter,
          zoom: 8
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var marker = new google.maps.Marker({
          position: mycenter,
          map: map
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);

      <% @reviews.each do |review| %>
      $(".score_<%= review.id %>").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= review.score %>,
        readOnly: true
      });
      <% end %>

      $(".average").raty({
        starOn: "<%= image_path('star-on.png') %>",
        starOff: "<%= image_path('star-off.png') %>",
        score: <%= @place.total_average_rating %>,
        readOnly: true
      });
    </script>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content, required: true %>
    <%= f.hidden_field :place_id, required: true, value: @place.id %>
    <%= f.hidden_field :score, required: true %>
    <div class="score"></div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script>

$(".score").raty({
	starOn: "<%= image_path('star-on.png') %>",
	starOff: "<%= image_path('star-off.png') %>",
	target: "#review_score",
	targetKeep: true,
	targetType: "number"
});

</script>

app/views/reviews/_review.html.erb
<p><%= gravatar_tag review.user.email, size: 20 %> <%= review.content %> by <%= review.user.name %><div class="score_<%= review.id %>"></div></p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>